import arepa
import os

c_iMinimum			= 10

#------------------------------------------------------------------------------ 

Import( "c_fileTaxa" )
Import( "pE" )

c_strFileIntactZIP	= arepa.c_strTmp + "intact.zip"
c_strFileIntactTXT	= arepa.c_strTmp + "intact.txt"
c_fileIntactC		= File( arepa.c_strTmp + "intactc" )
c_strProgIntact2C	= arepa.c_strSource + "intact2c.py"
c_strSConscriptID	= "SConscript.id"
c_strTXT			= ".txt"
c_strDir			= arepa.dir( pE )
Export( "c_fileIntactC" )

pE.Dir( arepa.c_strTmp )

arepa.download( pE, c_strFileIntactZIP,
	"ftp://ftp.ebi.ac.uk/pub/databases/intact/current/psimitab/intact.zip" )
pE.NoClean( c_strFileIntactZIP )

def funcIntactTXT( target, source, env ):
	
	strT, astrSs = arepa.ts( target, source )
	strBase = os.path.basename( strT )
	strDir = "psimitab/"
	return arepa.ex( " ".join( ("unzip", "-p", astrSs[0], strDir + strBase) ), strT )
pE.Command( c_strFileIntactTXT, c_strFileIntactZIP, funcIntactTXT )

arepa.pipe( pE, c_strFileIntactTXT, c_strProgIntact2C, c_fileIntactC,
	[[False, c_iMinimum], [True, c_fileTaxa]] )

def funcIntactTMP( target, source, env ):
	strT, astrSs = arepa.ts( target, source )
	for strLine in open( astrSs[0] ):
		if strLine.startswith( ">" ):
			env.SConscript( c_strDir + "/" + c_strSConscriptID,
				variant_dir = c_strDir + "/" + strLine[1:].strip( ), duplicate = 0 )
pE.Command( "intact.tmp", c_fileIntactC, funcIntactTMP )
