import arepa
import os
import sfle
import sys

pE = DefaultEnvironment( )

c_iMinimum			= 10
c_strSufTXT			= ".txt"
c_strURL			= "ftp://ftp.string-db.org/STRING/9.05/protein.actions.v9.05.txt.gz"

c_fileInputTaxIDs		= sfle.d( pE, arepa.path_arepa( ), sfle.c_strDirTmp, "taxids" )

c_fileGZ			= sfle.d( pE, sfle.c_strDirTmp, "string.txt.gz" )
c_fileC				= sfle.d( pE, sfle.c_strDirTmp, "stringc" )

c_fileProg2C			= sfle.d( pE, sfle.c_strDirSrc, "string2c.py" )

#===============================================================================
# Download the zip source file
#===============================================================================
sfle.download( pE, c_strURL, c_fileGZ )

#===============================================================================
# Process txt into the more compact txtc
#===============================================================================
afileC = sfle.pipe( pE, c_fileGZ, c_fileProg2C, c_fileC, [c_iMinimum, [c_fileInputTaxIDs]] )

#===============================================================================
# Pass the IDs from intactc to child directories
#===============================================================================

def funcScanner( target, source, env ):
	for strLine in open( str(source[0]) ):
		if strLine.startswith( ">" ):
			env["sconscript_child"]( target, source[0], env, strLine[1:].strip( ) )
sfle.sconscript_children( pE, afileC, funcScanner, 1, arepa.c_strProgSConstruct )
