import os, string
import repo_config as repoconfig
#import subdirs_processing_block as subdirs_block


def _download_taxdump_(target, source, env): 
	os.popen("wget -N " + repoconfig.shared_taxonomy_website)

def _untar_(target, source, env): 
	os.popen("tar -xzf " + source[0].rstr())

def _download_experiments_(target, source, env): 
	print "wget -N " + repoconfig.arrayexpress.data_website[0]
	os.popen("wget -N " + repoconfig.arrayexpress.data_website[0])

# command + 2 inputs + 1 output :  source = [command, input1, input2] target = [target1]
def _run_shellcmd_C21_ (target, source, env):	
	os.popen("./" + source[0].rstr() + " " + source[1].rstr() + " < " + source[2].rstr() + " > " + target[0].rstr()) 

def _process_data_(target, source, env): 
	os.popen("./" + source[0].rstr() + " < " + source[1].rstr())
	SConscript("SConscript")

def _create_kospcl_(target, source, env): 
	os.popen("Combiner E-*/*/*_w.txt | grep -v EWEIGHT | ruby ~/scripts/transpose.rb | KNNImputer -k 0 -m 0.333 -s 0 | \
		grep -v EWEIGHT | ruby ~/scripts/transpose.rb | KNNImputer -k 0 -m 0.333 -s 1 | "+\
		"ruby -pe \'$$_ =~ /^([^\t]+)(.*)/; if( $$. == 1 ); $$_ = $$1 + \"	NAME	GWEIGHT\"; elsif( $$1 == \"EWEIGHT\" ); "+\
			"$$_ = $$1 + \"		\"; else; $$_ = $$1 + \"\t\" + $$1 + \"	1\"; end; $$_ += $$2 + \"\n\"\' > " + target[0].rstr())

#KNNImputer -i <data.pcl> -o <imputed.pcl>

#kos.pcl:
#	Combiner E-*/*/*_w.txt | grep -v EWEIGHT | \
#		ruby ~/scripts/transpose.rb | KNNImputer -k 0 -m 0.333 -s 0 | \
#		grep -v EWEIGHT | ruby ~/scripts/transpose.rb | \
#		KNNImputer -k 0 -m 0.333 -s 1 | \
#		ruby -pe '$$_ =~ /^([^\t]+)(.*)/; if( $$. == 1 ); $$_ = $$1 + "	NAME	GWEIGHT"; elsif( $$1 == "EWEIGHT" ); $$_ = $$1 + "		"; else; $$_ = $$1 + "\t" + $$1 + "	1"; end; $$_ += $$2 + "\n"' > $@




env = Environment() 


#env.Command(['dwnld_taxdump'], [], _download_taxdump_) # TEMPORARY COMMENTED
#env.Command(['names.dmp', 'nodes.dmp'], ['taxdump.tar.gz', 'dwnld_taxdump'], _untar_)
env.Command(['names.dmp', 'nodes.dmp'], ['taxdump.tar.gz'], _untar_)
env.Command(['species.txt'], ['nodes2species.rb', 'names.dmp', 'nodes.dmp'], _run_shellcmd_C21_)

#env.Command(['dwnld_arrayexpress'], [], _download_experiments_)# TEMPORARY COMMENTED
#env.Command(['ids.txt'], ['experiments2ids.rb', 'species.txt', 'experiments','dwnld_arrayexpress'], _run_shellcmd_C21_)
env.Command(['ids.txt'], ['experiments2ids.rb', 'species.txt', 'experiments'], _run_shellcmd_C21_)


env.Command(['processdata'], ['subdirectories.rb', 'ids.txt'], _process_data_)
#env.Command(['run_subdirs'],['processdata'],subdirs_block._run_subdirectories_)

#env.Command(['kos.pcl'],['processdata','run_subdirs'],_create_kospcl_) 
env.Command(['kos.pcl'],['processdata'],_create_kospcl_) 