import os, string
import repo_config as repoconfig

def _download_taxdump_(target, source, env): 
	os.popen('wget -N ' + repoconfig.shared_taxonomy_website)

def _untar_(target, source, env): 
	os.popen('tar -xzf ' + source[0].rstr())

def _download_experiments_(target, source, env): 
	os.popen('wget -N ' + repoconfig.arrayexpress.data_website[0])

# command + 2 inputs + 1 output :  source = [command, input1, input2] target = [target1]
def _run_shellcmd_C21_ (target, source, env):	
	os.popen('./' + source[0].rstr() + ' ' + source[1].rstr() + ' < ' + source[2].rstr() + ' > ' + target[0].rstr()) 

def _process_data_(target, source, env): 
	os.popen('./' + source[0].rstr() + ' < ' + source[1].rstr())
	SConscript('SConscript')

#-------------------------This function currently not in use -------------------------------------#

def _create_kospcl_(target, source, env): 
	os.popen('Combiner E-*/*/*_w.txt | grep -v EWEIGHT > temp1')
	os.popen('ruby ../Scripts/transpose.rb < temp1 | KNNImputer -k 0 -m 0.333 -s 0 > temp2')
	os.popen('grep -v EWEIGHT temp2 | ruby ../Scripts/transpose.rb | KNNImputer -k 0 -m 0.333 -s 1 > temp3 ')

	in_f =open('temp3','r')
	out_f  = open(target[0].rstr(),'w')

	line = in_f.readline()
	line = string.split(line,'\t')
	line = line[:1] + ['NAME', 'GWEIGHT'] + line[1:]
	out_f.write(string.join(line,'\t'))  # check '\n'

	line  = ['EWEIGHT','',''] +  ['1']*(len(line)-3)
	out_f.write(string.join(line,'\t') + '\n')  # check '\n'
	
	while 1:
        	line = in_f.readline()
        	if line == '': break
		line = string.split(line,'\t')
		line = line[:1] + line[:1] + ['1'] + line[1:]
		out_f.write(string.join(line,'\t'))  # check '\n'
	
	in_f.close()
	out_f.close()

#------------------------------------------------------------------------------------------------#	
	
env = Environment() 

#env.Command(['dwnld_taxdump'], [], _download_taxdump_) # TEMPORARY COMMENTED

#env.Command(['names.dmp', 'nodes.dmp'], ['taxdump.tar.gz', 'dwnld_taxdump'], _untar_)# TEMPORARY COMMENTED replace with the following line
env.Command(['names.dmp', 'nodes.dmp'], ['taxdump.tar.gz'], _untar_)

env.Command(['species.txt'], ['nodes2species.rb', 'names.dmp', 'nodes.dmp'], _run_shellcmd_C21_)

#env.Command(['dwnld_arrayexpress'], [], _download_experiments_)# TEMPORARY COMMENTED

#env.Command(['ids.txt'], ['experiments2ids.rb', 'species.txt', 'experiments','dwnld_arrayexpress'], _run_shellcmd_C21_)# TEMPORARY COMMENTED replace with the following line
env.Command(['ids.txt'], ['experiments2ids.rb', 'species.txt', 'experiments'], _run_shellcmd_C21_)

env.Command(['processdata'], ['subdirectories.rb', 'ids.txt'], _process_data_)

#env.Command(['kos.pcl'],['processdata'],_create_kospcl_) 