"""
Transates RST README.txt document into 
web page, pdf file included with figures 
and all pertinent information 
"""

import sfle

c_strSufTEX          = ".tex"
c_fileInputREADMETXT = "README.txt"
c_fileProgRST2HTML   = "rst2html" 
c_fileProgRST2LATEX  = "rst2latex"
c_fileProgPDFLATEX   = "pdflatex"

pE = DefaultEnvironment( )

sfle.spipe( pE, c_fileInputREADMETXT, c_fileProgRST2HTML, sfle.rebase( c_fileInputREADMETXT, sfle.c_strSufTXT, sfle.c_strSufHTML ) )

fileTEX = sfle.spipe( pE, c_fileInputREADMETXT, c_fileProgRST2LATEX, sfle.rebase( c_fileInputREADMETXT, sfle.c_strSufTXT, c_strSufTEX ) )[0]

def pdflatex( target, source, env ):
	strT, astrSs = sfle.ts( target, source )
	return sfle.ex( (c_fileProgPDFLATEX, astrSs[0]) )
Command( sfle.rebase( fileTEX, c_strSufTEX, sfle.c_strSufPDF ), fileTEX, pdflatex )
